Try upgrading packages from the base image
plone/plone-backend pull request #103
Opened 2022-12-05 06:09 UTC by davisagli

See https://pythonspeed.com/articles/security-updates-in-docker/ for why to do this.

2022-12-05 10:46 UTC, Rudd-O commented
Thank you, this should absolutely be done.

2022-12-05 13:01 UTC, jensens requested changes

2022-12-05 13:01 UTC, jensens commented on Dockerfile
> +    apt-get -y upgrade
I don't think we need it in the intermediate image.

2022-12-05 19:00 UTC, davisagli commented on Dockerfile
> +    apt-get -y upgrade
@jensens If there is a security fix for a build tool, I would like it to be applied before I run the build tool and the exploit steals my build secrets.

2022-12-06 12:17 UTC, jensens commented on Dockerfile
> +    apt-get -y upgrade
You do a fresh install of the build tools anyway. Slim does not contain much. OTOH it does not hurt much ;)

2022-12-06 12:23 UTC, jensens approved these changes

2022-12-06 12:23 UTC, jensens commented
Is this WIP by intend?

2022-12-06 15:54 UTC, davisagli commented
It was WIP until I could see the result of the tests. Marking ready for review now.

2022-12-06 16:03 UTC, merged