add more configurable options via env vars
plone/plone-backend pull request #153
Opened 2024-11-11 10:12 UTC by erral

2024-11-12 04:10 UTC, davisagli requested changes

2024-11-12 04:10 UTC, davisagli commented on skeleton/docker-entrypoint.sh
> +[ -z ${ZOPE_FORM_MEMFILE_LIMIT+x} ] && export ZOPE_FORM_MEMFILE_LIMIT=4MB
We should keep the same defaults that were previously applied within Zope, unless you're intentionally changing them:
```suggestion
[ -z ${ZOPE_FORM_DISK_LIMIT+x} ] && export ZOPE_FORM_DISK_LIMIT=1GB
[ -z ${ZOPE_FORM_MEMFILE_LIMIT+x} ] && export ZOPE_FORM_MEMFILE_LIMIT=4KB
```

(compare https://github.com/zopefoundation/Zope/blob/04b75cf7956425fe3e4e1f4184bac4d377502c59/src/Zope2/Startup/wsgischema.xml#L133)

2024-11-12 06:57 UTC, erral commented
@1letter

2024-11-12 07:05 UTC, 1letter commented
@erral sholud not be the `max_request_body_size` config value also configurable in the `zope.ini` ?

```
[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = 8080
threads = 2
clear_untrusted_proxy_headers = false
max_request_body_size = 1073741824
```

2024-11-12 07:15 UTC, erral commented
> @erral sholud not be the `max_request_body_size` config value also configurable in the `zope.ini` ?
> 
> ```
> [server:main]
> use = egg:waitress#main
> host = 0.0.0.0
> port = 8080
> threads = 2
> clear_untrusted_proxy_headers = false
> max_request_body_size = 1073741824
> ```

Mmm.... right. Should it be like `ZOPE_FORM_MEMORY_LIMIT` or another new variable?

2024-11-12 08:04 UTC, 1letter commented
> Mmm.... right. Should it be `ZOPE_FORM_MEMORY_LIMIT` or another new variable?

`max_request_body_size` should be equal or greater `form-memory-limit`, for me is it not important how much vars are involved, the main thing is: it should be configurable ;-)

2024-11-22 08:55 UTC, erral commented
Sorry @1letter I don't know how to do this with environment variables, it looks like they are not available when building the ini file and we would require some kind of search and replace, but I don't know whether this is the right solution.

2025-01-28 04:34 UTC, davisagli approved these changes
Possibly zope.ini could be built from instance.yaml using cookiecutter-zope-instance at image build time, but that should probably be a separate PR. This one looks okay to me.

2025-01-28 04:46 UTC, davisagli commented
@erral I think the CI is failing on trying to log in to Docker Hub since you submitted this PR from a fork. Could you open a new one from a branch in this repository? I just sent an invite to the Installers team which should give you access.

2025-01-28 07:15 UTC, closed without merging

2025-01-28 07:16 UTC, erral commented
> @erral I think the CI is failing on trying to log in to Docker Hub since you submitted this PR from a fork. Could you open a new one from a branch in this repository? I just sent an invite to the Installers team which should give you access.

Done, thanks!